server:
    port: 8080

spring:
    data:
        mongodb:
            host: mongodb
            port: 27017
            database: async_db
    kafka:
        producer:
            bootstrap-servers: kafka:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
            group-id: group_id
        consumer:
            bootstrap-servers: kafka:9092
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            group-id: group_id

topic: order_flow

auto:
    create:
        topics:
            enable: true
